config/routes.rb
Rails.application.routes.draw do
  resources :photos
  devise_for :users
  root to: "pages#home"
  get '/project', to: 'pages#project'
  get '/slide', to: 'pages#slide'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/photo.rb
class Photo < ApplicationRecord
  has_one_attached :photo
  validates :title, presence: true
  validates :body, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable, :registerable
  devise :database_authenticatable, :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
  def project
    @photos = Photo.all
  end
  def slide
    @photos = Photo.all
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :set_photo, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, only: %i[ edit update destroy new create]
  # GET /photos or /photos.json
  def index
    @photos = Photo.all
  end

  # GET /photos/1 or /photos/1.json
  def show
  end

  # GET /photos/new
  def new
    @photo = Photo.new
  end

  # GET /photos/1/edit
  def edit
  end

  # POST /photos or /photos.json
  def create
    @photo = Photo.new(photo_params)

    respond_to do |format|
      if @photo.save
        format.html { redirect_to project_url, notice: "Photo was successfully created." }
        format.json { render json: { project_url: project_url }, status: :created }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /photos/1 or /photos/1.json
  def update
    respond_to do |format|
      if @photo.update(photo_params)
        format.html { redirect_to photo_url(@photo), notice: "Photo was successfully updated." }
        format.json { render :show, status: :ok, location: @photo }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /photos/1 or /photos/1.json
  def destroy
    @photo.destroy

    respond_to do |format|
      format.html { redirect_to project_url, notice: "Photo was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_photo
      @photo = Photo.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def photo_params
      params.require(:photo).permit(:title, :body, :photo)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Joshsproject</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=DM+Sans:opsz,wght@9..40,100&display=swap" rel="stylesheet">
  </head>

  <body>
    <%= yield %>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
  </body>
</html>

app/views/pages/home.html.erb
<body class="d-flex full-view text-center text-bg-dark">
    <svg xmlns="http://www.w3.org/2000/svg" class="d-none">
      <symbol id="check2" viewBox="0 0 16 16">
        <path d="M13.854 3.646a.5.5 0 0 1 0 .708l-7 7a.5.5 0 0 1-.708 0l-3.5-3.5a.5.5 0 1 1 .708-.708L6.5 10.293l6.646-6.647a.5.5 0 0 1 .708 0z"/>
      </symbol>
      <symbol id="circle-half" viewBox="0 0 16 16">
        <path d="M8 15A7 7 0 1 0 8 1v14zm0 1A8 8 0 1 1 8 0a8 8 0 0 1 0 16z"/>
      </symbol>
      <symbol id="moon-stars-fill" viewBox="0 0 16 16">
        <path d="M6 .278a.768.768 0 0 1 .08.858 7.208 7.208 0 0 0-.878 3.46c0 4.021 3.278 7.277 7.318 7.277.527 0 1.04-.055 1.533-.16a.787.787 0 0 1 .81.316.733.733 0 0 1-.031.893A8.349 8.349 0 0 1 8.344 16C3.734 16 0 12.286 0 7.71 0 4.266 2.114 1.312 5.124.06A.752.752 0 0 1 6 .278z"/>
        <path d="M10.794 3.148a.217.217 0 0 1 .412 0l.387 1.162c.173.518.579.924 1.097 1.097l1.162.387a.217.217 0 0 1 0 .412l-1.162.387a1.734 1.734 0 0 0-1.097 1.097l-.387 1.162a.217.217 0 0 1-.412 0l-.387-1.162A1.734 1.734 0 0 0 9.31 6.593l-1.162-.387a.217.217 0 0 1 0-.412l1.162-.387a1.734 1.734 0 0 0 1.097-1.097l.387-1.162zM13.863.099a.145.145 0 0 1 .274 0l.258.774c.115.346.386.617.732.732l.774.258a.145.145 0 0 1 0 .274l-.774.258a1.156 1.156 0 0 0-.732.732l-.258.774a.145.145 0 0 1-.274 0l-.258-.774a1.156 1.156 0 0 0-.732-.732l-.774-.258a.145.145 0 0 1 0-.274l.774-.258c.346-.115.617-.386.732-.732L13.863.1z"/>
      </symbol>
      <symbol id="sun-fill" viewBox="0 0 16 16">
        <path d="M8 12a4 4 0 1 0 0-8 4 4 0 0 0 0 8zM8 0a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 0zm0 13a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 13zm8-5a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2a.5.5 0 0 1 .5.5zM3 8a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2A.5.5 0 0 1 3 8zm10.657-5.657a.5.5 0 0 1 0 .707l-1.414 1.415a.5.5 0 1 1-.707-.708l1.414-1.414a.5.5 0 0 1 .707 0zm-9.193 9.193a.5.5 0 0 1 0 .707L3.05 13.657a.5.5 0 0 1-.707-.707l1.414-1.414a.5.5 0 0 1 .707 0zm9.193 2.121a.5.5 0 0 1-.707 0l-1.414-1.414a.5.5 0 0 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .707zM4.464 4.465a.5.5 0 0 1-.707 0L2.343 3.05a.5.5 0 1 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .708z"/>
      </symbol>
    </svg>
    </div>


<div class="cover-container d-flex w-100 p-3 mx-auto flex-column">
  <header class="mb-auto">
    <div>
      <h3 class="float-md-start mb-0">Seaside</h3>
      <nav class="nav nav-masthead justify-content-center float-md-end">
        <%= link_to "Home", root_path, class: "nav-link fw-bold py-1 px-0" %>
        <%# <a class="nav-link fw-bold py-1 px-0 active" aria-current="page" href="#">Home</a> %>
        <%# <a class="nav-link fw-bold py-1 px-0" href="#">Gallery</a> %>
        <%= link_to "Gallery",  project_path, class: "nav-link fw-bold py-1 px-0" %>
        <%# <a class="nav-link fw-bold py-1 px-0" href="#">Slide Show</a> %>
        <%= link_to "Slide Show",  slide_path, class: "nav-link fw-bold py-1 px-0" %>
      </nav>
    </div>
  </header>

<main class="px-3">
    <h1>Joshua Smith</h1>
    <p class="lead">Final photography submission with a seaside theme. Explore photographs through the gallery or slideshow.</p>
    <p class="lead">
      <%= link_to "Gallery",  project_path, class: "btn btn-lg btn-light fw-bold border-white bg-white" %>
      <%= link_to "Slide Show",  slide_path, class: "btn btn-lg btn-light fw-bold border-white bg-white" %>
    </p>
</main>

<footer class="mt-auto text-white-50">
    <p>Photography by Joshua Smith.</p>
</footer>
</div>
<script src="../assets/dist/js/bootstrap.bundle.min.js"></script>

</body>

app/views/pages/project.html.erb
<main class="top">

  <section class="py-5 text-center container">
    <div class="row py-lg-5">
      <div class="col-lg-6 col-md-8 mx-auto">
        <h1 class="fw-light">Seaside</h1>
        <p class="lead text-body-secondary">Something short and leading about the collection below—its contents, the creator, etc. Make it short and sweet, but not too short so folks don’t simply skip over it entirely.</p>
        <p>
          <%= link_to "Back to Homepage", root_path, class:"btn btn-lg btn-light fw-bold border-white bg-white" %>
          <%= link_to "Slideshow", slide_path, class:"btn btn-lg btn-light fw-bold border-white bg-white" %>
        </p>
      </div>
    </div>
  </section>
  <div>
    <% if user_signed_in? %>
      <%= button_to "New Photo", new_photo_path, method: :get, class: "btn btn-secondary my-2" %>
      <%= button_to "Sign Out", destroy_user_session_path, method: :delete, class: "btn btn-secondary my-2" %>
    <% end %>
  </div>
  <div class="album py-5 bg-body-tertiary">
    <div class="container">
      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
        <% @photos.each do |photo| %>
          <div class="col">
            <div class="card shadow-sm">
              <%# <svg class="bd-placeholder-img card-img-top" width="100%" height="225" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#55595c"/><text x="50%" y="50%" fill="#eceeef" dy=".3em">Thumbnail</text></svg> %>
              <%#= cl_image_tag photo.photo.key, crop: :fill, class: "bd-placeholder-img card-img-top", style: "width: 100; height: 225", fetch_format: "auto"%>
              <%= cl_image_tag photo.photo.key, crop: :fill, class: "bd-placeholder-img card-img-top", style: "width: 100%; height: 225px; object-fit: cover;", fetch_format: "auto" %>

              <div class="card-body">
                <p class="card-text"><%= photo.title %></p>
                <p class="card-text"><%= photo.body %></p>
                <div class="d-flex justify-content-between align-items-center">
                  <div class="btn-group">
                    <button type="button" class="btn btn-sm btn-outline-secondary" data-bs-toggle="modal" data-bs-target="#exampleModal<%= photo.id %>">
                      View Image
                    </button>
                      <% if user_signed_in? %>
                        <%= button_to "Edit Photo", edit_photo_path(photo), method: :get, class: "btn btn-sm btn-outline-secondary" %>
                        <%= button_to "Delete", photo_path(photo), method: :delete, class: "btn btn-sm btn-outline-secondary" %>
                      <% end %>
                    <!-- Modal -->
                    <div class="modal fade" id="exampleModal<%= photo.id %>" tabindex="-1" aria-labelledby="exampleModalLabel<%= photo.id %>" aria-hidden="true">
                      <div class="modal-dialog modal-fullscreen">
                        <div class="modal-content">
                          <div class="modal-header">
                            <h1 class="modal-title fs-5" id="exampleModalLabel<%= photo.id %>"><%= photo.title %></h1>
                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                          </div>
                          <div class="modal-body">
                            <%= cl_image_tag photo.photo.key, crop: :fill, class: "bd-placeholder-img card-img-top", style: "img-fluid", fetch_format: "auto"%>
                          </div>
                          <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                          </div>
                        </div>
                      </div>
                    </div>
                    <%# <% if user_signed_in? %>
                      <%#= button_to "Edit", edit_photo_path, class: "btn btn-sm btn-outline-secondary"%>
                    <%# <% end %>
                  </div>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>

</main>

<footer class="text-body-secondary py-5 top">
  <div class="container">
    <p class="float-end mb-1">
      <a href="#">Back to top</a>
    </p>
    <p class="mb-1">Joshua Smiths Final Project</p>
  </div>
</footer>
<script src="../assets/dist/js/bootstrap.bundle.min.js"></script>

</body>

app/views/pages/slide.html.erb
<body class="d-flex full-view text-center text-bg-dark">
    <svg xmlns="http://www.w3.org/2000/svg" class="d-none">
      <symbol id="check2" viewBox="0 0 16 16">
        <path d="M13.854 3.646a.5.5 0 0 1 0 .708l-7 7a.5.5 0 0 1-.708 0l-3.5-3.5a.5.5 0 1 1 .708-.708L6.5 10.293l6.646-6.647a.5.5 0 0 1 .708 0z"/>
      </symbol>
      <symbol id="circle-half" viewBox="0 0 16 16">
        <path d="M8 15A7 7 0 1 0 8 1v14zm0 1A8 8 0 1 1 8 0a8 8 0 0 1 0 16z"/>
      </symbol>
      <symbol id="moon-stars-fill" viewBox="0 0 16 16">
        <path d="M6 .278a.768.768 0 0 1 .08.858 7.208 7.208 0 0 0-.878 3.46c0 4.021 3.278 7.277 7.318 7.277.527 0 1.04-.055 1.533-.16a.787.787 0 0 1 .81.316.733.733 0 0 1-.031.893A8.349 8.349 0 0 1 8.344 16C3.734 16 0 12.286 0 7.71 0 4.266 2.114 1.312 5.124.06A.752.752 0 0 1 6 .278z"/>
        <path d="M10.794 3.148a.217.217 0 0 1 .412 0l.387 1.162c.173.518.579.924 1.097 1.097l1.162.387a.217.217 0 0 1 0 .412l-1.162.387a1.734 1.734 0 0 0-1.097 1.097l-.387 1.162a.217.217 0 0 1-.412 0l-.387-1.162A1.734 1.734 0 0 0 9.31 6.593l-1.162-.387a.217.217 0 0 1 0-.412l1.162-.387a1.734 1.734 0 0 0 1.097-1.097l.387-1.162zM13.863.099a.145.145 0 0 1 .274 0l.258.774c.115.346.386.617.732.732l.774.258a.145.145 0 0 1 0 .274l-.774.258a1.156 1.156 0 0 0-.732.732l-.258.774a.145.145 0 0 1-.274 0l-.258-.774a1.156 1.156 0 0 0-.732-.732l-.774-.258a.145.145 0 0 1 0-.274l.774-.258c.346-.115.617-.386.732-.732L13.863.1z"/>
      </symbol>
      <symbol id="sun-fill" viewBox="0 0 16 16">
        <path d="M8 12a4 4 0 1 0 0-8 4 4 0 0 0 0 8zM8 0a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 0zm0 13a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 13zm8-5a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2a.5.5 0 0 1 .5.5zM3 8a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2A.5.5 0 0 1 3 8zm10.657-5.657a.5.5 0 0 1 0 .707l-1.414 1.415a.5.5 0 1 1-.707-.708l1.414-1.414a.5.5 0 0 1 .707 0zm-9.193 9.193a.5.5 0 0 1 0 .707L3.05 13.657a.5.5 0 0 1-.707-.707l1.414-1.414a.5.5 0 0 1 .707 0zm9.193 2.121a.5.5 0 0 1-.707 0l-1.414-1.414a.5.5 0 0 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .707zM4.464 4.465a.5.5 0 0 1-.707 0L2.343 3.05a.5.5 0 1 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .708z"/>
      </symbol>
    </svg>
    </div>


<div class="cover-container d-flex w-100 p-3 mx-auto flex-column">
<header class="">
  <div>
    <h3 class="float-md-start mb-0">Seaside</h3>
    <nav class="nav nav-masthead justify-content-center float-md-end">
        <%= link_to "Home", root_path, class: "nav-link fw-bold py-1 px-0" %>
        <%# <a class="nav-link fw-bold py-1 px-0 active" aria-current="page" href="#">Home</a> %>
        <%# <a class="nav-link fw-bold py-1 px-0" href="#">Gallery</a> %>
        <%= link_to "Gallery",  project_path, class: "nav-link fw-bold py-1 px-0" %>
        <%# <a class="nav-link fw-bold py-1 px-0" href="#">Slide Show</a> %>
        <%= link_to "Slide Show",  slide_path, class: "nav-link fw-bold py-1 px-0" %>
    </nav>
  </div>
</header>

<div class="d-flex justify-content-center align-items-center" style="min-height: 80vh">
  <div class="carousel-container">
    <div id="carouselExampleIndicators" class="carousel slide" data-bs-ride="true" style="max-height: 80vh">
      <div class="carousel-indicators">
        <% @photos.each_with_index do |photo, index| %>
          <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="<%= index %>" class="<%= index == 0 ? 'active' : '' %>" aria-current="<%= index == 0 %>" aria-label="Slide <%= index + 1 %>"></button>
        <% end %>
      </div>
      <div class="carousel-inner">
        <% @photos.each_with_index do |photo, index| %>
          <div class="carousel-item <%= index == 0 ? 'active' : '' %>">
            <%= cl_image_tag photo.photo.key, crop: :fill, alt: photo.title, style: "max-height: 80%; max-width: 80%;"%>
          </div>
        <% end %>
      </div>
      <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
      </button>
      <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
      </button>
    </div>
  </div>
</div>

app/views/photos/_form.html.erb
<div class="full-height-container">
  <div class="centered-box">
    <div class="container">
      <div class="row">
        <div class="col-md-6 offset-md-3">
          <%= simple_form_for(@photo, html: { class: 'form-horizontal' }) do |f| %>
            <%= f.error_notification %>
            <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

            <div class="form-inputs">
              <%= f.input :title, label: 'Title' %>
              <%= f.input :body, label: 'Description' %>
              <div class="form-group">
                <div class="col-sm-10">
                  <%= f.input :photo, as: :file %>
                  <%# If you want to display the current photo, you can uncomment this section %>
                  <% if @photo.photo.present? %>
                  <div id="<%= dom_id(@photo, :photo)%>">
                  <%= image_tag @photo.photo.url, style: "max-width: 100%" %>
                  </div>
                  <% end %>
                </div>
              </div>
            </div>

            <div class="form-actions">
              <div class="col-sm-offset-2 col-sm-10">
                <%= f.button :submit, class: 'btn btn-primary' %>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/photos/_photo.html.erb
<div id="<%= dom_id photo %>">
  <p>
    <strong>Title:</strong>
    <%= photo.title %>
  </p>

  <p>
    <strong>Body:</strong>
    <%= photo.body %>
  </p>

</div>

app/views/photos/edit.html.erb
<h1 style="text-align: center; border-top: 2px solid #ccc; padding-top: 10px;">Edit Photo</h1>
<div style="text-align: center;">
  <%= link_to "Back to Project", project_path %>
</div>

<%= render "form", photo: @photo %>

app/views/photos/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Photos</h1>

<div id="photos">
  <% @photos.each do |photo| %>
    <%= render photo %>
    <p>
      <%= link_to "Show this photo", photo %>
    </p>
  <% end %>
</div>

<%= link_to "New photo", new_photo_path %>
<%= link_to "Back to Project", project_path %>

app/views/photos/new.html.erb
<h1 style="text-align: center; border-top: 2px solid #ccc; padding-top: 10px;">Add a Photo</h1>
<div style="text-align: center;">
  <%= link_to "Back to Project", project_path %>
</div>

<%= render "form", photo: @photo %>

<br>

app/views/photos/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @photo %>

<div>
  <%= link_to "Edit this photo", edit_photo_path(@photo) %> |
  <%= link_to "Back to photos", photos_path %>

  <%= button_to "Destroy this photo", @photo, method: :delete %>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>